# Generated by Django 5.0.1 on 2024-02-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='auther_image',
            new_name='author_image',
        ),
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('rental', 'Rental'), ('sold', 'Sold'), ('available', 'Available')], max_length=50),
        ),
    ]
