# Generated by Django 5.0.1 on 2024-02-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_rename_auther_books_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='auther',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='author_image',
            new_name='auther_image',
        ),
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('rental', 'rental'), ('sold', 'sold'), ('available', 'available')], max_length=50),
        ),
    ]
